---
# tasks file for remove-git-deploy-setup

- name: "Remove Git Bare Repo for site {{ item.url }}"
  file: 
    state: absent
    path: "{{ remove_git_deploy_setup_git_home }}/{{ item.url }}.git"
  with_items: '{{ remove_git_deploy_setup_sites_to_remove }}'
  ignore_errors: yes